version: '4'
services:

  app:
    build: .
    container_name: app
    ports:
      - "80:8001"
      - "443:443"
    restart: always
    volumes:
      - certbot-webroot-ppodeum:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
      -  ~/.aws/:/root/.aws

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-ppodeum:/webroots/ppodeum.site/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-ppodeum:
  certbot-letsencrypt:
~
~
