version: '4'
services:

  app:
    build: .
    container_name: app
    ports:
      - "8001:8001"
      - "443:443"
    restart: always
    volumes:
      - certbot-webroot-ppodeum:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
      -  ~/.aws/:/root/.aws

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-ppodeum:/webroots/ppodeum.site/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
  
  manager:
    build: ./hospitalAdmin
    container_name: manager
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  certbot-webroot-ppodeum:
  certbot-letsencrypt:
